docker:
  image: yegor256/rultor-image:1.13.0
install: |-
  sudo gem install texsc:0.6.0
  sudo gem install texqc:0.6.0
  sudo apt-get install -y aspell
  sudo tlmgr option repository ctan
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none install l3build
  git clone https://github.com/qpdf/qpdf && \
    cd qpdf && \
    cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo && \
    cmake --build build && \
    sudo cmake --install build && \
    cd .. && rm -rf qpdf && \
    export LD_LIBRARY_PATH=/usr/local/lib && sudo ldconfig && \
    qpdf --version
merge:
  script: |-
    l3build check
release:
  script: |-
    l3build tag ${tag}
    l3build ctan --show-log-on-error
    texsc
    texqc
    git commit -am "version set to ${tag}"
    echo 'y' | l3build upload --halt-on-error
