name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'qpdf/qpdf'
          path: 'qpdf'
      - run: cd qpdf && cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo && cmake --build build
      - uses: teatimeguest/setup-texlive-action@v2.5.0
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
          packages: scheme-basic xetex l3build
      - uses: actions/cache@v3
        with:
          path: qpdf
          key: qpdf
      - run: cd qpdf && tree
      - run: cp qpdf/target/qpdf /usr/local/bin
      - run: qpdf --version
      - run: l3build check -q --show-log-on-error
